CREATE DATABASE IF NOT EXISTS auth_user_db DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS product_db DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS trade_db DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS search_db DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS message_db DEFAULT CHARACTER SET utf8mb4;

USE auth_user_db;
CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    nickname VARCHAR(80) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    role_code VARCHAR(40) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

USE product_db;
CREATE TABLE IF NOT EXISTS product_spu (
    id BIGINT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(12, 2) NOT NULL,
    stock INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

USE trade_db;
CREATE TABLE IF NOT EXISTS order_info (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_amount DECIMAL(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

USE message_db;
CREATE TABLE IF NOT EXISTS notice (
    id BIGINT PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    publisher_id BIGINT,
    published TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);
